# Generated by Django 3.1.2 on 2020-10-02 20:56

from django.db import migrations, models
import django.db.models.deletion
import wagtail_color_panel.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailimages', '0022_uploadedimage'),
        ('wagtailcore', '0052_pagelogentry'),
    ]

    operations = [
        migrations.CreateModel(
            name='Appearance',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('button_action_bg_color_type', models.CharField(blank=True, choices=[('primary', 'Primary Color'), ('secondary', 'Secondary Color'), ('custom', 'Custom Color')], default='primary', help_text='Define primary and secondarz color in tab <a href="./#tab-branding">here</a>.', max_length=50, null=True, verbose_name='Color type')),
                ('button_action_bg_color', wagtail_color_panel.fields.ColorField(blank=True, help_text="Disable 'Color Type' to activate this field.", max_length=7, null=True, verbose_name='Color')),
                ('button_action_bg_color_hover', wagtail_color_panel.fields.ColorField(blank=True, max_length=7, null=True, verbose_name='Color (hover)')),
                ('button_action_text_color', wagtail_color_panel.fields.ColorField(blank=True, max_length=7, null=True, verbose_name='Text color')),
                ('button_action_text_color_hover', wagtail_color_panel.fields.ColorField(blank=True, max_length=7, null=True, verbose_name='Text color (hover)')),
                ('button_action_font_weight', models.CharField(blank=True, choices=[('font-hairline', 'Hairline'), ('font-thin', 'Thin'), ('font-light', 'Light'), ('font-normal', 'Default'), ('font-hairline', 'Hailine'), ('font-medium', 'Medium'), ('font-semibold', 'Semibold'), ('font-bold', 'Bold'), ('font-extrabold', 'Extrabold'), ('font-black', 'Black')], default='font-normal', max_length=50, null=True, verbose_name='Font weight')),
                ('button_action_padding', models.CharField(blank=True, choices=[('px-1 py-1', 'Small'), ('px-4 py-4', 'Medium'), ('px-8 py-8', 'Large'), ('px-12 py-12', 'X-Large')], max_length=50, null=True, verbose_name='Size')),
                ('button_action_border_radius', models.CharField(blank=True, choices=[('rounded-none', 'None'), ('rounded-sm', 'Small'), ('rounded-md', 'Medium'), ('rounded-lg', 'Large'), ('rounded-full', 'Full')], max_length=50, null=True, verbose_name='Edges')),
                ('navbar_layout_scheme', models.CharField(blank=True, choices=[('light_basic', 'Light'), ('dark_basic', 'Dark')], default='light', max_length=50, verbose_name='Color type')),
                ('navbar_background_color', wagtail_color_panel.fields.ColorField(blank=True, max_length=7, null=True, verbose_name='Background color')),
                ('navbar_font_color', wagtail_color_panel.fields.ColorField(blank=True, max_length=7, null=True, verbose_name='Font color')),
                ('navbar_fixed', models.BooleanField(default=False, verbose_name='Fixed')),
                ('navbar_transparent', models.BooleanField(default=False, verbose_name='Transparent')),
                ('color_primary', wagtail_color_panel.fields.ColorField(blank=True, help_text='Choose primary color.', max_length=7, null=True, verbose_name='Primary Color')),
                ('color_secondary', wagtail_color_panel.fields.ColorField(blank=True, help_text='Choose secondary color.', max_length=7, null=True, verbose_name='Secondary Color')),
                ('body_background_color_solid', wagtail_color_panel.fields.ColorField(blank=True, help_text='Choose background color', max_length=7, null=True, verbose_name='Background color')),
                ('favicon_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Favicon')),
                ('feedback_form_page', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='wagtailcore.page')),
                ('header_logo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Logo Image')),
                ('site', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='wagtailcore.site')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
