# Generated by Django 3.1.2 on 2020-10-02 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appearance',
            name='navbar_layout_scheme',
        ),
    ]
