# Generated by Django 3.0.9 on 2020-08-26 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Header',
        ),
    ]
