# Generated by Django 3.0.9 on 2020-08-30 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Layout',
        ),
    ]
