# Generated by Django 3.1.2 on 2020-10-02 21:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0002_remove_appearance_navbar_layout_scheme'),
    ]

    operations = [
        migrations.AddField(
            model_name='appearance',
            name='navbar_color_scheme',
            field=models.CharField(blank=True, choices=[('light_basic', 'Light'), ('dark_basic', 'Dark')], default='light', max_length=50, verbose_name='Color type'),
        ),
        migrations.AddField(
            model_name='appearance',
            name='navbar_layout_scheme',
            field=models.CharField(blank=True, choices=[('light_basic', 'Light'), ('dark_basic', 'Dark')], default='light', max_length=50, verbose_name='Layout Scheme'),
        ),
    ]
