# Generated by Django 3.1.2 on 2020-10-04 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0003_auto_20201002_2103'),
    ]

    operations = [
        migrations.AddField(
            model_name='appearance',
            name='navbar_background_active',
            field=models.BooleanField(default=False, verbose_name='Enable'),
        ),
    ]
