# Generated by Django 3.0.9 on 2020-08-30 16:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0003_header'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Header',
        ),
    ]
