# Generated by Django 3.0.9 on 2020-09-02 18:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0022_uploadedimage'),
        ('wagtailcore', '0052_pagelogentry'),
        ('theme', '0004_layout_bad'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Layout',
            new_name='Appearance',
        ),
    ]
