# Generated by Django 3.1.2 on 2020-10-05 22:27

from django.db import migrations, models
import wagtail_color_panel.fields


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0004_appearance_navbar_background_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='appearance',
            name='navbar_background_color_2',
            field=wagtail_color_panel.fields.ColorField(blank=True, max_length=7, null=True, verbose_name='Color 2'),
        ),
        migrations.AddField(
            model_name='appearance',
            name='section_background_type',
            field=models.CharField(blank=True, choices=[('transparent', 'Transparent'), ('solid', 'Solid Color'), ('gradient', 'Gradient Color'), ('image', 'Background Image')], help_text='Transparent background will use the background-color "page settings".', max_length=100, null=True, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='appearance',
            name='button_action_bg_color_hover',
            field=wagtail_color_panel.fields.ColorField(blank=True, max_length=7, null=True, verbose_name='On hover'),
        ),
        migrations.AlterField(
            model_name='appearance',
            name='button_action_bg_color_type',
            field=models.CharField(blank=True, choices=[('primary', 'Primary Color'), ('secondary', 'Secondary Color'), ('custom', 'Custom Color')], default='primary', help_text='Define primary and secondarz color in tab <a href="./#tab-branding">here</a>.', max_length=50, null=True, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='appearance',
            name='button_action_font_weight',
            field=models.CharField(blank=True, choices=[('font-hairline', 'Hairline'), ('font-thin', 'Thin'), ('font-light', 'Light'), ('font-normal', 'Default'), ('font-hairline', 'Hailine'), ('font-medium', 'Medium'), ('font-semibold', 'Semibold'), ('font-bold', 'Bold'), ('font-extrabold', 'Extrabold'), ('font-black', 'Black')], default='font-normal', max_length=50, null=True, verbose_name='Weight'),
        ),
        migrations.AlterField(
            model_name='appearance',
            name='button_action_text_color',
            field=wagtail_color_panel.fields.ColorField(blank=True, max_length=7, null=True, verbose_name='Color'),
        ),
        migrations.AlterField(
            model_name='appearance',
            name='button_action_text_color_hover',
            field=wagtail_color_panel.fields.ColorField(blank=True, max_length=7, null=True, verbose_name='On hover'),
        ),
        migrations.AlterField(
            model_name='appearance',
            name='navbar_background_active',
            field=models.BooleanField(default=False, verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='appearance',
            name='navbar_background_color',
            field=wagtail_color_panel.fields.ColorField(blank=True, max_length=7, null=True, verbose_name='Color 1'),
        ),
    ]
