# Generated by Django 3.0.9 on 2020-08-30 16:50

from django.db import migrations
import wagtail_color_panel.fields


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0005_layout'),
    ]

    operations = [
        migrations.AlterField(
            model_name='layout',
            name='body_background_color',
            field=wagtail_color_panel.fields.ColorField(blank=True, help_text='Choose background color', max_length=7, null=True),
        ),
    ]
