# Generated by Django 3.0.9 on 2020-09-02 19:37

from django.db import migrations, models
import django.db.models.deletion
import wagtail_color_panel.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0022_uploadedimage'),
        ('theme', '0005_auto_20200902_1859'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appearance',
            name='bad',
        ),
        migrations.AddField(
            model_name='appearance',
            name='navbar_layout_scheme',
            field=models.CharField(blank=True, choices=[('navbar-light', 'Light - for use with a light-colored navbar'), ('navbar-dark', 'Dark - for use with a dark-colored navbar')], default='navbar-light', help_text='Optimizes text and other navbar elements for use with light or dark backgrounds.', max_length=50, verbose_name='Navbar color scheme'),
        ),
        migrations.AlterField(
            model_name='appearance',
            name='body_background_color_solid',
            field=wagtail_color_panel.fields.ColorField(blank=True, help_text='Choose background color', max_length=7, null=True, verbose_name='Background color'),
        ),
        migrations.AlterField(
            model_name='appearance',
            name='header_background_color',
            field=wagtail_color_panel.fields.ColorField(blank=True, help_text='Choose background color', max_length=7, null=True, verbose_name='Background color'),
        ),
        migrations.AlterField(
            model_name='appearance',
            name='header_logo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image', verbose_name='Logo image'),
        ),
    ]
