# Generated by Django 3.0.9 on 2020-09-02 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0006_auto_20200902_1937'),
    ]

    operations = [
        migrations.AddField(
            model_name='appearance',
            name='navbar_collapse_mode',
            field=models.CharField(blank=True, choices=[('', 'Never show menu - Always collapse menu behind a button'), ('navbar-expand-sm', 'sm - Show on small screens (phone size) and larger'), ('navbar-expand-md', 'md - Show on medium screens (tablet size) and larger'), ('navbar-expand-lg', 'lg - Show on large screens (laptop size) and larger'), ('navbar-expand-xl', 'xl - Show on extra large screens (desktop, wide monitor)')], default='navbar-expand-lg', help_text='Control on what screen sizes to show and collapse the navbar menu links.', max_length=50, verbose_name='Collapse navbar menu'),
        ),
        migrations.AddField(
            model_name='appearance',
            name='navbar_color_scheme',
            field=models.CharField(blank=True, choices=[('navbar-light', 'Light - for use with a light-colored navbar'), ('navbar-dark', 'Dark - for use with a dark-colored navbar')], default='navbar-light', help_text='Optimizes text and other navbar elements for use with light or dark backgrounds.', max_length=50, verbose_name='Navbar color scheme'),
        ),
        migrations.AddField(
            model_name='appearance',
            name='navbar_content_fluid',
            field=models.BooleanField(default=False, help_text='Content within the navbar will fill edge to edge.', verbose_name='Full width navbar contents'),
        ),
        migrations.AddField(
            model_name='appearance',
            name='navbar_fixed',
            field=models.BooleanField(default=False, help_text='Fixed navbar will remain at the top of the page when scrolling.', verbose_name='Fixed navbar'),
        ),
        migrations.AddField(
            model_name='appearance',
            name='navbar_format',
            field=models.CharField(blank=True, choices=[('', 'Default Bootstrap Navbar'), ('codered-navbar-center', 'Centered logo at top')], default='', max_length=50, verbose_name='Navbar format'),
        ),
        migrations.AddField(
            model_name='appearance',
            name='navbar_search',
            field=models.BooleanField(default=True, help_text='Show search box in navbar', verbose_name='Search box'),
        ),
        migrations.AddField(
            model_name='appearance',
            name='navbar_wrapper_fluid',
            field=models.BooleanField(default=True, help_text='The navbar will fill edge to edge.', verbose_name='Full width navbar'),
        ),
    ]
