# Generated by Django 3.0.10 on 2020-09-06 11:00

from django.db import migrations
import wagtail_color_panel.fields


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0007_auto_20200902_1949'),
    ]

    operations = [
        migrations.AddField(
            model_name='appearance',
            name='button_action_bg_color',
            field=wagtail_color_panel.fields.ColorField(blank=True, help_text='Choose background color', max_length=7, null=True, verbose_name='Background color'),
        ),
    ]
