# Generated by Django 3.0.10 on 2020-09-06 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0008_appearance_button_action_bg_color'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Appearance',
        ),
    ]
