# Generated by Django 3.1.2 on 2020-10-06 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0009_auto_20201006_2040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appearance',
            name='navbar_height',
            field=models.CharField(blank=True, choices=[('h-12', 'Small'), ('h-16', 'Medium'), ('h-20', 'Large'), ('h-24', 'X-Large')], default='h-16', max_length=50, null=True, verbose_name='Height'),
        ),
        migrations.AlterField(
            model_name='appearance',
            name='navbar_top_bottom_padding',
            field=models.CharField(blank=True, choices=[('py-0', 'None'), ('py-24', 'Small'), ('py-40', 'Medium'), ('py-56', 'Large'), ('py-64', 'X-Large')], default='py-40', max_length=50, null=True, verbose_name='Padding'),
        ),
    ]
