# Generated by Django 3.0.10 on 2020-09-06 11:33

from django.db import migrations
import wagtail_color_panel.fields


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0010_appearance'),
    ]

    operations = [
        migrations.AddField(
            model_name='appearance',
            name='button_action_bg_color_hover',
            field=wagtail_color_panel.fields.ColorField(blank=True, help_text='Choose hover background color', max_length=7, null=True, verbose_name='Background hover color'),
        ),
        migrations.AddField(
            model_name='appearance',
            name='button_action_text_color',
            field=wagtail_color_panel.fields.ColorField(blank=True, help_text='Choose text color', max_length=7, null=True, verbose_name='Text color'),
        ),
        migrations.AddField(
            model_name='appearance',
            name='button_action_text_color_hover',
            field=wagtail_color_panel.fields.ColorField(blank=True, help_text='Choose text hover color', max_length=7, null=True, verbose_name='Text hover color'),
        ),
    ]
