# Generated by Django 3.0.10 on 2020-09-06 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0011_auto_20200906_1133'),
    ]

    operations = [
        migrations.AddField(
            model_name='appearance',
            name='button_action_font_weight',
            field=models.CharField(blank=True, choices=[('font-hairline', 'Hailine'), ('font-thin', 'Thin'), ('font-light', 'Light'), ('font-normal', 'Normal'), ('font-hairline', 'Hailine'), ('font-medium', 'Medium'), ('font-semibold', 'Semibold'), ('font-bold', 'Bold'), ('font-extrabold', 'Extrabold'), ('font-black', 'Black')], default='font-normal', help_text='Optimizes text and other navbar elements for use with light or dark backgrounds.', max_length=50, null=True, verbose_name='Navbar color scheme'),
        ),
    ]
