# Generated by Django 3.0.10 on 2020-09-06 11:50

from django.db import migrations, models
import wagtail_color_panel.fields


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0012_appearance_button_action_font_weight'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appearance',
            name='button_action_bg_color',
            field=wagtail_color_panel.fields.ColorField(blank=True, help_text='Choose background color.', max_length=7, null=True, verbose_name='Background color'),
        ),
        migrations.AlterField(
            model_name='appearance',
            name='button_action_font_weight',
            field=models.CharField(blank=True, choices=[('font-hairline', 'Hairline'), ('font-thin', 'Thin'), ('font-light', 'Light'), ('font-normal', 'Normal'), ('font-hairline', 'Hailine'), ('font-medium', 'Medium'), ('font-semibold', 'Semibold'), ('font-bold', 'Bold'), ('font-extrabold', 'Extrabold'), ('font-black', 'Black')], help_text='Choose font weight.', max_length=50, null=True, verbose_name='Font weight'),
        ),
        migrations.AlterField(
            model_name='appearance',
            name='button_action_text_color',
            field=wagtail_color_panel.fields.ColorField(blank=True, help_text='Choose text color.', max_length=7, null=True, verbose_name='Text color'),
        ),
        migrations.AlterField(
            model_name='appearance',
            name='button_action_text_color_hover',
            field=wagtail_color_panel.fields.ColorField(blank=True, help_text='Choose text hover color.', max_length=7, null=True, verbose_name='Text hover color'),
        ),
    ]
