# Generated by Django 3.0.10 on 2020-09-06 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0013_auto_20200906_1150'),
    ]

    operations = [
        migrations.AddField(
            model_name='appearance',
            name='button_action_padding_top_bottom',
            field=models.CharField(blank=True, choices=[('py-0', 'No padding'), ('py-1', 'Sall padding'), ('py-2', 'Medium padding'), ('py-3', 'Large padding'), ('py-4', 'X-Large padding')], help_text='Choose padding for top and bottom.', max_length=50, null=True, verbose_name='Padding Top/Bottom'),
        ),
    ]
