# Generated by Django 3.0.10 on 2020-09-06 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0014_appearance_button_action_padding_top_bottom'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appearance',
            name='button_action_padding_top_bottom',
        ),
        migrations.AddField(
            model_name='appearance',
            name='button_action_size',
            field=models.CharField(blank=True, choices=[('py-0', 'None'), ('py-1', 'Small'), ('py-2', 'Medium'), ('py-3', 'Large'), ('py-4', 'X-Large')], help_text='Choose button size.', max_length=50, null=True, verbose_name='Button Size'),
        ),
    ]
