# Generated by Django 3.0.10 on 2020-09-06 12:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0015_auto_20200906_1212'),
    ]

    operations = [
        migrations.AddField(
            model_name='appearance',
            name='button_action_border_radius',
            field=models.CharField(blank=True, choices=[('px-0 py-0', 'None'), ('px-1 py-1', 'Small'), ('px-2 py-2', 'Medium'), ('px-3 py-3', 'Large'), ('px-4 py-4', 'X-Large')], help_text='Choose button edges.', max_length=50, null=True, verbose_name='Edges'),
        ),
        migrations.AlterField(
            model_name='appearance',
            name='button_action_size',
            field=models.CharField(blank=True, choices=[('px-0 py-0', 'None'), ('px-1 py-1', 'Small'), ('px-2 py-2', 'Medium'), ('px-3 py-3', 'Large'), ('px-4 py-4', 'X-Large')], help_text='Choose button size.', max_length=50, null=True, verbose_name='Size'),
        ),
    ]
