# Generated by Django 3.0.10 on 2020-09-06 12:25

from django.db import migrations
import wagtail_color_panel.fields


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0016_auto_20200906_1223'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appearance',
            old_name='button_action_size',
            new_name='button_action_padding',
        ),
        migrations.AlterField(
            model_name='appearance',
            name='button_action_bg_color',
            field=wagtail_color_panel.fields.ColorField(blank=True, help_text='Choose background color.', max_length=7, null=True, verbose_name='Color'),
        ),
        migrations.AlterField(
            model_name='appearance',
            name='button_action_bg_color_hover',
            field=wagtail_color_panel.fields.ColorField(blank=True, help_text='Choose hover background color', max_length=7, null=True, verbose_name='Color (hover)'),
        ),
        migrations.AlterField(
            model_name='appearance',
            name='button_action_text_color_hover',
            field=wagtail_color_panel.fields.ColorField(blank=True, help_text='Choose text hover color.', max_length=7, null=True, verbose_name='Text color (hover)'),
        ),
    ]
