# Generated by Django 3.0.10 on 2020-09-06 14:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0017_auto_20200906_1225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appearance',
            name='button_action_border_radius',
            field=models.CharField(blank=True, choices=[('rounded-none', 'None'), ('rounded-sm', 'Small'), ('rounded', 'Normal'), ('rounded-md', 'Medium'), ('rounded-lg', 'Large'), ('rounded-full', 'Full')], default='rounded', help_text='Choose button edges.', max_length=50, null=True, verbose_name='Edges'),
        ),
        migrations.AlterField(
            model_name='appearance',
            name='button_action_font_weight',
            field=models.CharField(blank=True, choices=[('font-hairline', 'Hairline'), ('font-thin', 'Thin'), ('font-light', 'Light'), ('font-normal', 'Normal'), ('font-hairline', 'Hailine'), ('font-medium', 'Medium'), ('font-semibold', 'Semibold'), ('font-bold', 'Bold'), ('font-extrabold', 'Extrabold'), ('font-black', 'Black')], default='font-normal', help_text='Choose font weight.', max_length=50, null=True, verbose_name='Font weight'),
        ),
        migrations.AlterField(
            model_name='appearance',
            name='button_action_padding',
            field=models.CharField(blank=True, choices=[('px-1 py-1', 'Small'), ('px-2 py-2', 'Normal'), ('px-4 py-4', 'Medium'), ('px-8 py-8', 'Large'), ('px-12 py-12', 'X-Large')], default='px-2 py-2', help_text='Choose button size.', max_length=50, null=True, verbose_name='Size'),
        ),
    ]
