# Generated by Django 3.0.10 on 2020-09-06 14:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0018_auto_20200906_1445'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appearance',
            name='button_action_padding',
            field=models.CharField(blank=True, choices=[('px-1 py-1', 'Small'), ('px-2 py-2', 'Normal'), ('px-4 py-4', 'Medium'), ('px-8 py-8', 'Large'), ('px-12 py-12', 'X-Large')], default='Normal', help_text='Choose button size.', max_length=50, null=True, verbose_name='Size'),
        ),
    ]
