# Generated by Django 3.0.10 on 2020-09-06 22:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0023_auto_20200906_2159'),
    ]

    operations = [
        migrations.AddField(
            model_name='appearance',
            name='button_action_bg_color_type',
            field=models.CharField(choices=[('primary', 'Primary Color'), ('secondary', 'Secondary Color'), ('custom', 'Custom Color')], default='primary', help_text='Choose color type.', max_length=50, null=True, verbose_name='Color Type'),
        ),
        migrations.AlterField(
            model_name='appearance',
            name='button_action_border_radius',
            field=models.CharField(blank=True, choices=[('rounded-none', 'None'), ('rounded-sm', 'Small'), ('rounded-md', 'Medium'), ('rounded-lg', 'Large'), ('rounded-full', 'Full')], help_text='Choose button edges.', max_length=50, null=True, verbose_name='Edges'),
        ),
    ]
