# Generated by Django 3.0.10 on 2020-09-07 18:12

from django.db import migrations, models
import wagtail_color_panel.fields


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0025_auto_20200907_1747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appearance',
            name='button_action_bg_color_type',
            field=models.CharField(blank=True, choices=[('primary', 'Primary Color'), ('secondary', 'Secondary Color'), ('custom', 'Custom Color')], default='primary', help_text='Choose color type.', max_length=50, null=True, verbose_name='Color Type'),
        ),
        migrations.AlterField(
            model_name='appearance',
            name='color_primary',
            field=wagtail_color_panel.fields.ColorField(blank=True, help_text='Choose primary color.', max_length=7, null=True, verbose_name='Primary Color'),
        ),
        migrations.AlterField(
            model_name='appearance',
            name='color_secondary',
            field=wagtail_color_panel.fields.ColorField(blank=True, help_text='Choose secondary color.', max_length=7, null=True, verbose_name='Secondary Color'),
        ),
    ]
