# Generated by Django 3.0.10 on 2020-09-15 19:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0026_auto_20200907_1812'),
    ]

    operations = [
        migrations.RenameField(
            model_name='appearance',
            old_name='header_background_color',
            new_name='navbar_background_color',
        ),
        migrations.RemoveField(
            model_name='appearance',
            name='navbar_layout_scheme',
        ),
    ]
