# Generated by Django 3.0.10 on 2020-09-15 19:20

from django.db import migrations
import wagtail_color_panel.fields


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0027_auto_20200915_1914'),
    ]

    operations = [
        migrations.AddField(
            model_name='appearance',
            name='navbar_font_color',
            field=wagtail_color_panel.fields.ColorField(blank=True, help_text='Choose font color', max_length=7, null=True, verbose_name='Font color'),
        ),
    ]
