# Generated by Django 3.0.10 on 2020-09-15 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0028_appearance_navbar_font_color'),
    ]

    operations = [
        migrations.AddField(
            model_name='appearance',
            name='navbar_transparent',
            field=models.BooleanField(default=False, help_text='Fixed navbar will remain at the top of the page when scrolling.', verbose_name='Transparent navbar'),
        ),
    ]
