# Generated by Django 3.0.10 on 2020-09-15 22:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0052_pagelogentry'),
        ('theme', '0029_appearance_navbar_transparent'),
    ]

    operations = [
        migrations.AddField(
            model_name='appearance',
            name='feedback_form_page',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='wagtailcore.Page'),
        ),
        migrations.AlterField(
            model_name='appearance',
            name='navbar_color_scheme',
            field=models.CharField(blank=True, choices=[('light_basic', 'Light'), ('dark_basic', 'Dark')], default='navbar-light', help_text='Optimizes text and other navbar elements for use with light or dark backgrounds.', max_length=50, verbose_name='Color scheme'),
        ),
        migrations.AlterField(
            model_name='appearance',
            name='navbar_fixed',
            field=models.BooleanField(default=False, help_text='Fixed navbar will remain at the top of the page when scrolling.', verbose_name='Fixed'),
        ),
        migrations.AlterField(
            model_name='appearance',
            name='navbar_transparent',
            field=models.BooleanField(default=False, help_text='Fixed navbar will remain at the top of the page when scrolling.', verbose_name='Transparent'),
        ),
    ]
