# Generated by Django 3.0.10 on 2020-09-16 08:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0030_auto_20200915_2210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appearance',
            name='navbar_color_scheme',
            field=models.CharField(blank=True, choices=[('light_basic', 'Light'), ('dark_basic', 'Dark')], default='navbar-light', help_text='A call to action button (CTA), depending on the situation, will usually prompt users to sign up/register/buy now/etc. CTA buttons should be used where the platform wants to strongly suggest something that the user should do.', max_length=50, verbose_name='Color scheme'),
        ),
    ]
