# Generated by Django 3.0.10 on 2020-09-17 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0032_auto_20200917_1747'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Footer',
        ),
    ]
