# Generated by Django 3.0.10 on 2020-09-17 17:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0052_pagelogentry'),
        ('theme', '0033_delete_footer'),
    ]

    operations = [
        migrations.AddField(
            model_name='appearance',
            name='feedback_form_page',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='wagtailcore.Page'),
        ),
    ]
