# Generated by Django 3.0.10 on 2020-09-21 19:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0022_uploadedimage'),
        ('theme', '0034_appearance_feedback_form_page'),
    ]

    operations = [
        migrations.AddField(
            model_name='appearance',
            name='favicon_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image', verbose_name='Favicon'),
        ),
        migrations.AlterField(
            model_name='appearance',
            name='header_logo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image', verbose_name='Logo Image'),
        ),
    ]
