# Generated by Django 3.0.10 on 2020-09-21 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0037_auto_20200921_2049'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='appearance',
            name='navbar_content_fluid',
        ),
        migrations.RemoveField(
            model_name='appearance',
            name='navbar_wrapper_fluid',
        ),
        migrations.AlterField(
            model_name='appearance',
            name='navbar_fixed',
            field=models.BooleanField(default=False, verbose_name='Fixed'),
        ),
        migrations.AlterField(
            model_name='appearance',
            name='navbar_transparent',
            field=models.BooleanField(default=False, verbose_name='Transparent'),
        ),
    ]
