# Generated by Django 3.0.10 on 2020-09-21 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0039_auto_20200921_2104'),
    ]

    operations = [
        migrations.AlterField(
            model_name='appearance',
            name='button_action_bg_color_type',
            field=models.CharField(blank=True, choices=[('primary', 'Primary Color'), ('secondary', 'Secondary Color'), ('custom', 'Custom Color')], default='primary', help_text='Define primary and secondarz color in tab <a href="./#tab-branding">here</a>.', max_length=50, null=True, verbose_name='Color type'),
        ),
    ]
