version: '3'

services:
  python:
    build:
      context: .
      dockerfile: docker/prod/python/Dockerfile
    environment:
      - DJANGO_SETTINGS_MODULE=core.settings.prod
      - PYTHONUNBUFFERED=1
    volumes:
      - /statics/wagtail-cms/static_files:/app/static
      - /statics/wagtail-cms/media_files:/app/media
    ports:
      - 8000:8000
    command: gunicorn -w 4 core.wsgi -b 0.0.0.0:8000

