version: '3'

volumes:
  db:

services:
  python:
    build:
      context: .
      dockerfile: docker/prod/python/Dockerfile
    environment:
      - DJANGO_SETTINGS_MODULE=core.settings.production
      - PYTHONUNBUFFERED=1
    volumes:
      - /statics/wagtail-cms/static_files:/app/static
      - /statics/wagtail-cms/media_files:/app/media
      - db:/app/db
    ports:
      - 7000:8000
    command: gunicorn -w 4 core.wsgi -b 0.0.0.0:8000
    networks:
      static-network:
        ipv4_address: 172.20.128.2
networks:
  static-network:
    ipam:
      config:
        - subnet: 172.20.0.0/16
