version: '3'

volumes:
  db.sqlite3

services:
  python:
    build:
      context: .
      dockerfile: docker/prod/python/Dockerfile
    environment:
      - DJANGO_SETTINGS_MODULE=core.settings.production
      - PYTHONUNBUFFERED=1
    volumes:
      - /statics/wagtail-cms/static_files:/app/static
      - /statics/wagtail-cms/media_files:/app/media
    ports:
      - 7000:8000
    command: gunicorn -w 4 core.wsgi -b 0.0.0.0:8000
    volumes:
      - db.sqlite3:/app/db.sqlite3

