# Generated by Django 3.0.10 on 2020-09-15 18:14

from django.db import migrations
import wagtail.core.blocks
import wagtail.core.fields


class Migration(migrations.Migration):

    dependencies = [
        ('snippets', '0002_auto_20200910_1659'),
    ]

    operations = [
        migrations.AlterField(
            model_name='herosection',
            name='hero_buttons',
            field=wagtail.core.fields.StreamField([('action_button', wagtail.core.blocks.StructBlock([('text', wagtail.core.blocks.CharBlock(label='Text', max_length=50, required=True))])), ('primary_button', wagtail.core.blocks.StructBlock([('text', wagtail.core.blocks.CharBlock(label='Text', max_length=50, required=True))]))], help_text='Please choose Buttons', null=True, verbose_name='Buttons'),
        ),
    ]
