# Generated by Django 3.0.10 on 2020-09-16 08:15

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0022_uploadedimage'),
        ('wagtailcore', '0052_pagelogentry'),
        ('wagtailforms', '0004_add_verbose_name_plural'),
        ('wagtailredirects', '0006_redirect_increase_max_length'),
        ('wagtailmenus', '0023_remove_use_specific'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('theme', '0031_auto_20200916_0815'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('form', '0009_formindexpage'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='FormPage',
            new_name='FormSection',
        ),
    ]
