# Generated by Django 3.0.10 on 2020-09-19 11:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('theme', '0034_appearance_feedback_form_page'),
        ('wagtailcore', '0052_pagelogentry'),
        ('wagtailmenus', '0023_remove_use_specific'),
        ('wagtailforms', '0004_add_verbose_name_plural'),
        ('wagtailredirects', '0006_redirect_increase_max_length'),
        ('form', '0010_auto_20200916_0815'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formsection',
            name='page_ptr',
        ),
        migrations.RemoveField(
            model_name='formsection',
            name='search_image',
        ),
        migrations.DeleteModel(
            name='FormField',
        ),
        migrations.DeleteModel(
            name='FormSection',
        ),
    ]
