# Generated by Django 3.0.10 on 2020-09-19 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailredirects', '0006_redirect_increase_max_length'),
        ('theme', '0034_appearance_feedback_form_page'),
        ('wagtailcore', '0052_pagelogentry'),
        ('wagtailforms', '0004_add_verbose_name_plural'),
        ('wagtailmenus', '0023_remove_use_specific'),
        ('form', '0011_auto_20200919_1119'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FormIndexPage',
        ),
    ]
