# Generated by Django 3.0.9 on 2020-08-16 20:45

from django.db import migrations
import streams.blocks.default
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.embeds.blocks
import wagtail.images.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('flex', '0013_auto_20200729_0607'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flexpage',
            name='content',
            field=wagtail.core.fields.StreamField([('hero', wagtail.core.blocks.StructBlock([('layout', wagtail.core.blocks.ChoiceBlock(choices=[('simple_centered', 'Simple centered'), ('image_right', 'Image on right')], classname='wagtailuiplus__choice-handler')), ('title', wagtail.core.blocks.CharBlock(classname='wagtailuiplus__show_if image_right', help_text='Add your Title', required=False)), ('title2', wagtail.core.blocks.CharBlock(classname='wagtailuiplus__show_if simple_centered', help_text='Add your Title', required=False)), ('text', wagtail.core.blocks.RichTextBlock(help_text='Add your Text', required=True))])), ('text_and_image', wagtail.core.blocks.StructBlock([('background', wagtail.core.blocks.ChoiceBlock(choices=[('red', 'red-value'), ('blue', 'blue-value')])), ('text', wagtail.core.blocks.CharBlock()), ('left_column', wagtail.core.blocks.StreamBlock([('heading', wagtail.core.blocks.CharBlock(classname='full title')), ('paragraph', wagtail.core.blocks.RichTextBlock()), ('image', wagtail.images.blocks.ImageChooserBlock()), ('embedded_video', wagtail.embeds.blocks.EmbedBlock()), ('google_map', wagtail.core.blocks.StructBlock([('map_long', wagtail.core.blocks.CharBlock(max_length=255, required=True)), ('map_lat', wagtail.core.blocks.CharBlock(max_length=255, required=True)), ('map_zoom_level', wagtail.core.blocks.CharBlock(default=14, max_length=3, required=True))]))], icon='arrow-left', label='Left column content')), ('right_column', wagtail.core.blocks.StreamBlock([('heading', wagtail.core.blocks.CharBlock(classname='full title')), ('paragraph', wagtail.core.blocks.RichTextBlock()), ('image', wagtail.images.blocks.ImageChooserBlock()), ('embedded_video', wagtail.embeds.blocks.EmbedBlock()), ('google_map', wagtail.core.blocks.StructBlock([('map_long', wagtail.core.blocks.CharBlock(max_length=255, required=True)), ('map_lat', wagtail.core.blocks.CharBlock(max_length=255, required=True)), ('map_zoom_level', wagtail.core.blocks.CharBlock(default=14, max_length=3, required=True))]))], icon='arrow-right', label='Right column content'))])), ('title_and_text', wagtail.core.blocks.StructBlock([('title', wagtail.core.blocks.CharBlock(help_text='Add your Title', required=True)), ('text', wagtail.core.blocks.TextBlock(help_text='Add additional Text', required=True))])), ('full_richtext', streams.blocks.default.RichTextBlock()), ('simple_richtext', streams.blocks.default.SimpleRichTextBlock())], blank=True, null=True),
        ),
    ]
