# Generated by Django 3.0.9 on 2020-08-26 19:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('subscribers', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subscribers',
            options={'verbose_name': 'Subscribers', 'verbose_name_plural': 'Subscribers'},
        ),
    ]
