# Generated by Django 3.0.10 on 2020-09-04 23:53

from django.db import migrations, models
import django.db.models.deletion
import section.models
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.snippets.blocks
import wagtail_color_panel.fields
import wagtailmetadata.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0052_pagelogentry'),
        ('wagtailimages', '0022_uploadedimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='SectionPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('body', wagtail.core.fields.StreamField([('test', wagtail.core.blocks.StructBlock([('hero_section', wagtail.snippets.blocks.SnippetChooserBlock(section.models.HeroSection))]))], blank=True)),
                ('search_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image', verbose_name='Search image')),
            ],
            options={
                'verbose_name': 'Section Page',
                'verbose_name_plural': 'Section Pages',
            },
            bases=(wagtailmetadata.models.MetadataMixin, 'wagtailcore.page', models.Model),
        ),
        migrations.CreateModel(
            name='HeroSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True, verbose_name='Title')),
                ('background_type', models.CharField(blank=True, choices=[('transparent', 'Transparent'), ('solid', 'Solid Color'), ('gradient', 'Gradient Color'), ('image', 'Background Image')], default='trasparent', help_text='Transparent background will use the background-color "page settings".', max_length=100, null=True)),
                ('background_color', wagtail_color_panel.fields.ColorField(blank=True, help_text='Choose background color', max_length=7, null=True, verbose_name='Background color')),
                ('background_color_2', wagtail_color_panel.fields.ColorField(blank=True, help_text='Choose background color', max_length=7, null=True, verbose_name='Background color 2')),
                ('heading', models.CharField(blank=True, default='We are heroes', max_length=100, null=True, verbose_name='Hero title')),
                ('layout', models.CharField(blank=True, choices=[('simple_centered', 'Simple centered'), ('image_right', 'Image on right')], default='simple_centered', max_length=100, verbose_name='Layout')),
                ('subheading', models.CharField(blank=True, default='What business are you?', help_text='Leave field empty to hide.', max_length=100, verbose_name='Hero subtitle')),
                ('description', models.TextField(blank=True, default='The thing we do is better than any other similar thing and this hero panel will convince you of that, just by having a glorious background image.', help_text='Leave field empty to hide.', max_length=400, verbose_name='Hero description')),
                ('button_text', models.CharField(blank=True, default='Subscribe', help_text='Leave field empty to hide.', max_length=100, verbose_name='Hero button text')),
                ('image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtailimages.Image', verbose_name='Image')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
