# Generated by Django 3.0.10 on 2020-09-23 19:56

import section.sections.feature_section
import section.sections.form_section
import section.sections.hero_section
from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.fields
import wagtail.snippets.blocks
import wagtailmetadata.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('wagtailcore', '0052_pagelogentry'),
        ('wagtailimages', '0022_uploadedimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='Section',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
            ],
            options={
                'verbose_name': 'Section',
                'verbose_name_plural': 'Sections',
            },
            bases=('wagtailcore.page',),
        ),
        migrations.CreateModel(
            name='SectionPage',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('body', wagtail.core.fields.StreamField([('hero_section', wagtail.snippets.blocks.SnippetChooserBlock(section.sections.hero_section.HeroSection, icon='placeholder', template='sections/hero_section.html')), ('feature_section', wagtail.snippets.blocks.SnippetChooserBlock(section.sections.feature_section.FeatureSection, icon='list-ul', template='sections/feature_section.html')), ('form_section', wagtail.snippets.blocks.SnippetChooserBlock(section.sections.form_section.FormSection, can_choose_root=False, icon='list-ul', template='sections/form_section.html'))], blank=True)),
                ('search_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image', verbose_name='Search image')),
            ],
            options={
                'verbose_name': 'Section Page',
                'verbose_name_plural': 'Section Pages',
            },
            bases=(wagtailmetadata.models.MetadataMixin, 'wagtailcore.page', models.Model),
        ),
    ]
