# Generated by Django 3.0.9 on 2020-09-03 20:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0022_uploadedimage'),
        ('section', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='herosection',
            name='background_color',
        ),
        migrations.AddField(
            model_name='herosection',
            name='button_text',
            field=models.CharField(blank=True, default='Subscribe', help_text='Leave field empty to hide.', max_length=100, verbose_name='Hero button text'),
        ),
        migrations.AddField(
            model_name='herosection',
            name='description',
            field=models.TextField(blank=True, default='The thing we do is better than any other similar thing and this hero panel will convince you of that, just by having a glorious background image.', help_text='Leave field empty to hide.', max_length=400, verbose_name='Hero description'),
        ),
        migrations.AddField(
            model_name='herosection',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtailimages.Image', verbose_name='Image'),
        ),
        migrations.AddField(
            model_name='herosection',
            name='layout',
            field=models.CharField(blank=True, choices=[('simple_centered', 'Simple centered'), ('image_right', 'Image on right')], default='simple_centered', max_length=100, verbose_name='Layout'),
        ),
        migrations.AddField(
            model_name='herosection',
            name='subheading',
            field=models.CharField(blank=True, default='What business are you?', help_text='Leave field empty to hide.', max_length=100, verbose_name='Hero subtitle'),
        ),
    ]
