# Generated by Django 3.0.10 on 2020-09-05 00:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('section', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='herosection',
            old_name='description',
            new_name='hero_description',
        ),
        migrations.RenameField(
            model_name='herosection',
            old_name='button_text',
            new_name='hero_first_button_text',
        ),
        migrations.RenameField(
            model_name='herosection',
            old_name='heading',
            new_name='hero_heading',
        ),
        migrations.RenameField(
            model_name='herosection',
            old_name='image',
            new_name='hero_image',
        ),
        migrations.RenameField(
            model_name='herosection',
            old_name='layout',
            new_name='hero_layout',
        ),
        migrations.RenameField(
            model_name='herosection',
            old_name='subheading',
            new_name='hero_subheading',
        ),
        migrations.RenameField(
            model_name='herosection',
            old_name='background_color',
            new_name='section_background_color',
        ),
        migrations.RenameField(
            model_name='herosection',
            old_name='background_color_2',
            new_name='section_background_color_2',
        ),
        migrations.RenameField(
            model_name='herosection',
            old_name='background_type',
            new_name='section_background_type',
        ),
        migrations.RenameField(
            model_name='herosection',
            old_name='title',
            new_name='section_name',
        ),
        migrations.AddField(
            model_name='herosection',
            name='hero_second_button_text',
            field=models.CharField(blank=True, default='Subscribe', help_text='Leave field empty to hide.', max_length=100, verbose_name='Hero button text'),
        ),
    ]
