# Generated by Django 3.1.2 on 2020-10-06 22:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('section', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='herosection',
            name='hero_image_size',
            field=models.CharField(choices=[('max-w-2xl', 'Small'), ('max-w-4xl', 'Medium'), ('container', 'Large'), ('max-w-full', 'Full')], default='h-16', max_length=50, verbose_name='Image size'),
        ),
    ]
