# Generated by Django 3.0.10 on 2020-09-26 15:14

import section.sections.feature_section
import section.sections.form_section
import section.sections.hero_section
import section.sections.subscription_section
from django.db import migrations
import wagtail.core.fields
import wagtail.snippets.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('section', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sectionpage',
            name='body',
            field=wagtail.core.fields.StreamField([('hero_section', wagtail.snippets.blocks.SnippetChooserBlock(section.sections.hero_section.HeroSection, icon='placeholder', template='sections/hero_section.html')), ('feature_section', wagtail.snippets.blocks.SnippetChooserBlock(section.sections.feature_section.FeatureSection, icon='list-ul', template='sections/feature_section.html')), ('form_section', wagtail.snippets.blocks.SnippetChooserBlock(section.sections.form_section.FormSection, can_choose_root=False, icon='list-ul', template='sections/form_section.html')), ('subscription_section', wagtail.snippets.blocks.SnippetChooserBlock(section.sections.subscription_section.SubscriptionSection, can_choose_root=False, icon='list-ul', template='sections/subscription_section.html'))], blank=True),
        ),
    ]
