# Generated by Django 3.1.2 on 2020-10-06 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('section', '0002_herosection_hero_image_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='herosection',
            name='hero_action_type_1',
            field=models.CharField(choices=[('action_button', 'Action button')], default='action_button', max_length=50, verbose_name='Action type (First)'),
        ),
        migrations.AddField(
            model_name='herosection',
            name='hero_action_type_2',
            field=models.CharField(choices=[('action_button', 'Action button')], default='action_button', max_length=50, verbose_name='Action type (Second)'),
        ),
        migrations.AlterField(
            model_name='herosection',
            name='hero_image_size',
            field=models.CharField(choices=[('max-w-xs', 'X-Small'), ('max-w-sm', 'Small'), ('max-w-md', 'Medium'), ('max-w-lg', 'Large'), ('max-w-xl', 'X-Large'), ('max-w-full', 'Full')], default='max-w-md', max_length=50, verbose_name='Image size'),
        ),
    ]
