# Generated by Django 3.0.10 on 2020-09-07 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('section', '0002_auto_20200907_1945'),
    ]

    operations = [
        migrations.AddField(
            model_name='herosection',
            name='hero_description',
            field=models.TextField(blank=True, default='The thing we do is better than any other similar thing and this hero panel will convince you of that, just by having a glorious background image.', help_text='Leave field empty to hide.', max_length=400, verbose_name='Hero description'),
        ),
        migrations.AddField(
            model_name='herosection',
            name='hero_heading',
            field=models.CharField(blank=True, default='We are heroes', max_length=100, null=True, verbose_name='Hero title'),
        ),
        migrations.AddField(
            model_name='herosection',
            name='hero_layout',
            field=models.CharField(blank=True, choices=[('simple_centered', 'Simple centered'), ('image_right', 'Image on right')], default='simple_centered', max_length=100, verbose_name='Layout'),
        ),
        migrations.AddField(
            model_name='herosection',
            name='hero_subheading',
            field=models.CharField(blank=True, default='What business are you?', help_text='Leave field empty to hide.', max_length=100, verbose_name='Hero subtitle'),
        ),
    ]
