# Generated by Django 3.0.9 on 2020-09-03 21:04

from django.db import migrations
import wagtail_color_panel.fields


class Migration(migrations.Migration):

    dependencies = [
        ('section', '0002_auto_20200903_2031'),
    ]

    operations = [
        migrations.AddField(
            model_name='sectionbase',
            name='background_color',
            field=wagtail_color_panel.fields.ColorField(blank=True, help_text='Choose background color', max_length=7, null=True, verbose_name='Background color'),
        ),
        migrations.AddField(
            model_name='sectionbase',
            name='background_color_2',
            field=wagtail_color_panel.fields.ColorField(blank=True, help_text='Choose background color', max_length=7, null=True, verbose_name='Background color 2'),
        ),
    ]
