# Generated by Django 3.1.2 on 2020-10-07 06:24

from django.db import migrations, models
import django.db.models.deletion
import wagtail.core.fields
import wagtail_color_panel.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0052_pagelogentry'),
        ('wagtailimages', '0022_uploadedimage'),
        ('section', '0003_auto_20201006_2252'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContentSection',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.page')),
                ('section_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Title')),
                ('section_heading', models.CharField(blank=True, default='We are heroes', max_length=100, null=True, verbose_name='Hero title')),
                ('section_subheading', models.CharField(blank=True, default='What business are you?', help_text="Leave field empty to hide. <a href='/contract.pdf'>contract</a>.", max_length=100, null=True, verbose_name='Hero subtitle')),
                ('section_description', models.TextField(blank=True, default='The thing we do is better than any other similar thing and this hero panel will convince you of that, just by having a glorious background image.', help_text='Leave field empty to hide.', max_length=400, null=True, verbose_name='Hero description')),
                ('section_background_type', models.CharField(blank=True, choices=[('transparent', 'Transparent'), ('solid', 'Solid Color'), ('gradient', 'Gradient Color'), ('image', 'Background Image')], default='trasparent', help_text='Transparent background will use the background-color "page settings".', max_length=100, null=True, verbose_name='Type')),
                ('section_background_color', wagtail_color_panel.fields.ColorField(blank=True, help_text='Choose background color', max_length=7, null=True, verbose_name='Color 1')),
                ('section_background_color_2', wagtail_color_panel.fields.ColorField(blank=True, help_text='Choose background color', max_length=7, null=True, verbose_name='Color 2')),
                ('section_color_theme', models.CharField(blank=True, choices=[('light', 'Light'), ('dark', 'Dark')], max_length=50, null=True, verbose_name='Theme')),
                ('section_top_bottom_padding', models.CharField(blank=True, choices=[('py-0', 'None'), ('py-24', 'Small'), ('py-40', 'Medium'), ('py-56', 'Large'), ('py-64', 'X-Large')], default='py-40', max_length=50, null=True, verbose_name='Height')),
                ('section_container_width', models.CharField(blank=True, choices=[('container max-w-2xl', 'Small'), ('container max-w-4xl', 'Medium'), ('container', 'Large'), ('container max-w-full', 'Full')], default='container', max_length=50, null=True, verbose_name='Width')),
                ('content_richtext', wagtail.core.fields.RichTextField()),
                ('section_background_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.image', verbose_name='Image')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page', models.Model),
        ),
    ]
