# Generated by Django 3.0.10 on 2020-09-06 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('section', '0003_herosection_padding_top'),
    ]

    operations = [
        migrations.AlterField(
            model_name='herosection',
            name='padding_top',
            field=models.CharField(blank=True, db_column='new_padding_top', max_length=100, null=True),
        ),
    ]
