# Generated by Django 3.0.9 on 2020-09-03 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('section', '0003_auto_20200903_2104'),
    ]

    operations = [
        migrations.AddField(
            model_name='sectionbase',
            name='background_type',
            field=models.CharField(blank=True, choices=[('transparent', 'Transparent'), ('solid', 'Solid Color'), ('gradient', 'Gradient Color'), ('image', 'Background Image')], help_text='Transparent background will use the background-color "page settings".', max_length=100),
        ),
    ]
