# Generated by Django 3.1.2 on 2020-10-02 12:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailredirects', '0006_redirect_increase_max_length'),
        ('wagtailcore', '0052_pagelogentry'),
        ('wagtailforms', '0004_add_verbose_name_plural'),
        ('theme', '0040_auto_20200921_2138'),
        ('wagtailmenus', '0023_remove_use_specific'),
        ('section', '0003_featuresection_formfield_formindexpage_formsection_herosection_subscriptionsection'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Section',
        ),
    ]
