# Generated by Django 3.0.10 on 2020-09-06 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('section', '0004_auto_20200906_0706'),
    ]

    operations = [
        migrations.AlterField(
            model_name='herosection',
            name='padding_top',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
