# Generated by Django 3.0.10 on 2020-09-07 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('section', '0004_auto_20200907_1946'),
    ]

    operations = [
        migrations.AddField(
            model_name='herosection',
            name='section_description',
            field=models.TextField(blank=True, default='The thing we do is better than any other similar thing and this hero panel will convince you of that, just by having a glorious background image.', help_text='Leave field empty to hide.', max_length=400, verbose_name='Hero description'),
        ),
        migrations.AddField(
            model_name='herosection',
            name='section_heading',
            field=models.CharField(blank=True, default='We are heroes', max_length=100, null=True, verbose_name='Hero title'),
        ),
        migrations.AddField(
            model_name='herosection',
            name='section_subheading',
            field=models.CharField(blank=True, default='What business are you?', help_text='Leave field empty to hide.', max_length=100, verbose_name='Hero subtitle'),
        ),
    ]
