# Generated by Django 3.1.2 on 2020-10-07 08:29

from django.db import migrations
import section.sections.content_section
import section.sections.feature_section
import section.sections.form_section
import section.sections.hero_section
import section.sections.subscription_section
import wagtail.core.fields
import wagtail.snippets.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('section', '0004_contentsection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sectionpage',
            name='body',
            field=wagtail.core.fields.StreamField([('hero_section', wagtail.snippets.blocks.SnippetChooserBlock(section.sections.hero_section.HeroSection, icon='placeholder', template='sections/hero_section.html')), ('feature_section', wagtail.snippets.blocks.SnippetChooserBlock(section.sections.feature_section.FeatureSection, icon='list-ul', template='sections/feature_section.html')), ('content_section', wagtail.snippets.blocks.SnippetChooserBlock(section.sections.content_section.ContentSection, icon='list-ul', template='sections/content_section.html')), ('form_section', wagtail.snippets.blocks.SnippetChooserBlock(section.sections.form_section.FormSection, can_choose_root=False, icon='list-ul', template='sections/form_section.html')), ('subscription_section', wagtail.snippets.blocks.SnippetChooserBlock(section.sections.subscription_section.SubscriptionSection, can_choose_root=False, icon='list-ul', template='sections/subscription_section.html'))], blank=True),
        ),
    ]
