# Generated by Django 3.0.10 on 2020-09-07 19:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('section', '0005_auto_20200907_1947'),
    ]

    operations = [
        migrations.AddField(
            model_name='herosection',
            name='hero_layout',
            field=models.CharField(blank=True, choices=[('simple_centered', 'Simple centered'), ('image_right', 'Image on right')], default='simple_centered', max_length=100, verbose_name='Layout'),
        ),
    ]
