# Generated by Django 3.0.10 on 2020-09-06 08:38

from django.db import migrations
import section.models


class Migration(migrations.Migration):

    dependencies = [
        ('section', '0006_mymixinmodeltest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mymixinmodeltest',
            name='myfield',
            field=section.models.MyMixinCharField(db_column='new_myfield', max_length=512, new_arg='myarg'),
        ),
    ]
