# Generated by Django 3.0.10 on 2020-09-07 19:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0022_uploadedimage'),
        ('section', '0006_herosection_hero_layout'),
    ]

    operations = [
        migrations.AddField(
            model_name='herosection',
            name='section_background_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtailimages.Image', verbose_name='Background image'),
        ),
    ]
