# Generated by Django 3.0.10 on 2020-09-06 08:39

from django.db import migrations, models
import section.models


class Migration(migrations.Migration):

    dependencies = [
        ('section', '0007_auto_20200906_0838'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyMixinAbsctractModelTest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('myfield', section.models.MyMixinCharField(db_column='new_myfield', max_length=512, new_arg='myarg')),
            ],
        ),
        migrations.DeleteModel(
            name='MyMixinModelTest',
        ),
    ]
