# Generated by Django 3.0.10 on 2020-09-08 18:48

from django.db import migrations, models
import django.db.models.deletion
import wagtail_color_panel.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0022_uploadedimage'),
        ('section', '0007_herosection_section_background_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='herosection',
            name='section_background_color',
            field=wagtail_color_panel.fields.ColorField(blank=True, help_text='Choose background color', max_length=7, null=True, verbose_name='Color 1'),
        ),
        migrations.AlterField(
            model_name='herosection',
            name='section_background_color_2',
            field=wagtail_color_panel.fields.ColorField(blank=True, help_text='Choose background color', max_length=7, null=True, verbose_name='Color 2'),
        ),
        migrations.CreateModel(
            name='FeatureSection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Title')),
                ('section_heading', models.CharField(blank=True, default='We are heroes', max_length=100, null=True, verbose_name='Hero title')),
                ('section_subheading', models.CharField(blank=True, default='What business are you?', help_text='Leave field empty to hide.', max_length=100, verbose_name='Hero subtitle')),
                ('section_description', models.TextField(blank=True, default='The thing we do is better than any other similar thing and this hero panel will convince you of that, just by having a glorious background image.', help_text='Leave field empty to hide.', max_length=400, verbose_name='Hero description')),
                ('section_background_type', models.CharField(blank=True, choices=[('transparent', 'Transparent'), ('solid', 'Solid Color'), ('gradient', 'Gradient Color'), ('image', 'Background Image')], default='trasparent', help_text='Transparent background will use the background-color "page settings".', max_length=100, null=True)),
                ('section_background_color', wagtail_color_panel.fields.ColorField(blank=True, help_text='Choose background color', max_length=7, null=True, verbose_name='Color 1')),
                ('section_background_color_2', wagtail_color_panel.fields.ColorField(blank=True, help_text='Choose background color', max_length=7, null=True, verbose_name='Color 2')),
                ('feature_layout', models.CharField(choices=[('simple-centered', 'Simple centered')], default='simple-centered', max_length=50, null=True, verbose_name='Layout')),
                ('feautre_column_count', models.CharField(choices=[('grid-cols-2', 'Two'), ('rid-cols-3', 'Three'), ('grid-cols-4', 'Four')], default='grid-cols-3', max_length=50, null=True, verbose_name='Number of columns')),
                ('section_background_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtailimages.Image', verbose_name='Background image')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
