# Generated by Django 3.0.10 on 2020-09-06 13:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('section', '0008_auto_20200906_0839'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MyMixinAbsctractModelTest',
        ),
    ]
