# Generated by Django 3.0.10 on 2020-09-06 13:11

from django.db import migrations
import section.models
import wagtail.core.blocks
import wagtail.core.fields
import wagtail.snippets.blocks


class Migration(migrations.Migration):

    dependencies = [
        ('section', '0012_auto_20200906_1309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sectionpage',
            name='body',
            field=wagtail.core.fields.StreamField([('test', wagtail.core.blocks.StructBlock([('section', wagtail.snippets.blocks.SnippetChooserBlock(section.models.HeroSection))]))], blank=True),
        ),
    ]
