# Generated by Django 3.0.10 on 2020-09-06 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('section', '0014_auto_20200906_1726'),
    ]

    operations = [
        migrations.AlterField(
            model_name='herosection',
            name='button_action_padding',
            field=models.CharField(blank=True, choices=[('px-1 py-1', 'Small'), ('px-4 py-4', 'Medium'), ('px-8 py-8', 'Large'), ('px-12 py-12', 'X-Large')], help_text='Choose button size.', max_length=50, null=True, verbose_name='Size'),
        ),
    ]
