# Generated by Django 3.0.10 on 2020-09-06 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('section', '0015_auto_20200906_2146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='herosection',
            name='button_action_border_radius',
            field=models.CharField(blank=True, choices=[('rounded', 'Default'), ('rounded-none', 'None'), ('rounded-sm', 'Small'), ('rounded-md', 'Medium'), ('rounded-lg', 'Large'), ('rounded-full', 'Full')], help_text='Choose button edges.', max_length=50, null=True, verbose_name='Edges'),
        ),
    ]
