# Generated by Django 3.0.10 on 2020-09-07 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('section', '0017_auto_20200906_2230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='herosection',
            name='button_action_bg_color_type',
            field=models.CharField(blank=True, choices=[('primary', 'Primary Color'), ('secondary', 'Secondary Color'), ('custom', 'Custom Color')], default='primary', help_text='Choose color type.', max_length=50, null=True, verbose_name='Color Type'),
        ),
    ]
