# Generated by Django 3.0.10 on 2020-09-19 12:40

from django.db import migrations, models
import django.db.models.deletion
import wagtail_color_panel.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0022_uploadedimage'),
        ('components', '0003_formfield_formsection'),
    ]

    operations = [
        migrations.AddField(
            model_name='formsection',
            name='section_background_color',
            field=wagtail_color_panel.fields.ColorField(blank=True, help_text='Choose background color', max_length=7, null=True, verbose_name='Color 1'),
        ),
        migrations.AddField(
            model_name='formsection',
            name='section_background_color_2',
            field=wagtail_color_panel.fields.ColorField(blank=True, help_text='Choose background color', max_length=7, null=True, verbose_name='Color 2'),
        ),
        migrations.AddField(
            model_name='formsection',
            name='section_background_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtailimages.Image', verbose_name='Background image'),
        ),
        migrations.AddField(
            model_name='formsection',
            name='section_background_type',
            field=models.CharField(blank=True, choices=[('transparent', 'Transparent'), ('solid', 'Solid Color'), ('gradient', 'Gradient Color'), ('image', 'Background Image')], default='trasparent', help_text='Transparent background will use the background-color "page settings".', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='formsection',
            name='section_description',
            field=models.TextField(blank=True, default='The thing we do is better than any other similar thing and this hero panel will convince you of that, just by having a glorious background image.', help_text='Leave field empty to hide.', max_length=400, verbose_name='Hero description'),
        ),
        migrations.AddField(
            model_name='formsection',
            name='section_heading',
            field=models.CharField(blank=True, default='We are heroes', max_length=100, null=True, verbose_name='Hero title'),
        ),
        migrations.AddField(
            model_name='formsection',
            name='section_name',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Title'),
        ),
        migrations.AddField(
            model_name='formsection',
            name='section_subheading',
            field=models.CharField(blank=True, default='What business are you?', help_text='Leave field empty to hide.', max_length=100, verbose_name='Hero subtitle'),
        ),
    ]
