# Generated by Django 3.0.10 on 2020-09-20 08:49

from django.db import migrations, models
import wagtail_color_panel.fields


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0004_auto_20200919_1240'),
    ]

    operations = [
        migrations.AddField(
            model_name='formsection',
            name='button_action_bg_color',
            field=wagtail_color_panel.fields.ColorField(blank=True, help_text='Choose background color.', max_length=7, null=True, verbose_name='Color'),
        ),
        migrations.AddField(
            model_name='formsection',
            name='button_action_bg_color_hover',
            field=wagtail_color_panel.fields.ColorField(blank=True, help_text='Choose hover background color', max_length=7, null=True, verbose_name='Color (hover)'),
        ),
        migrations.AddField(
            model_name='formsection',
            name='button_action_bg_color_type',
            field=models.CharField(blank=True, choices=[('primary', 'Primary Color'), ('secondary', 'Secondary Color'), ('custom', 'Custom Color')], default='primary', help_text='Choose color type.', max_length=50, null=True, verbose_name='Color Type'),
        ),
        migrations.AddField(
            model_name='formsection',
            name='button_action_border_radius',
            field=models.CharField(blank=True, choices=[('rounded-none', 'None'), ('rounded-sm', 'Small'), ('rounded-md', 'Medium'), ('rounded-lg', 'Large'), ('rounded-full', 'Full')], help_text='Choose button edges.', max_length=50, null=True, verbose_name='Edges'),
        ),
        migrations.AddField(
            model_name='formsection',
            name='button_action_font_weight',
            field=models.CharField(choices=[('font-hairline', 'Hairline'), ('font-thin', 'Thin'), ('font-light', 'Light'), ('font-normal', 'Default'), ('font-hairline', 'Hailine'), ('font-medium', 'Medium'), ('font-semibold', 'Semibold'), ('font-bold', 'Bold'), ('font-extrabold', 'Extrabold'), ('font-black', 'Black')], default='font-normal', help_text='Choose font weight.', max_length=50, null=True, verbose_name='Font weight'),
        ),
        migrations.AddField(
            model_name='formsection',
            name='button_action_padding',
            field=models.CharField(blank=True, choices=[('px-1 py-1', 'Small'), ('px-4 py-4', 'Medium'), ('px-8 py-8', 'Large'), ('px-12 py-12', 'X-Large')], help_text='Choose button size.', max_length=50, null=True, verbose_name='Size'),
        ),
        migrations.AddField(
            model_name='formsection',
            name='button_action_text_color',
            field=wagtail_color_panel.fields.ColorField(blank=True, help_text='Choose text color.', max_length=7, null=True, verbose_name='Text color'),
        ),
        migrations.AddField(
            model_name='formsection',
            name='button_action_text_color_hover',
            field=wagtail_color_panel.fields.ColorField(blank=True, help_text='Choose text hover color.', max_length=7, null=True, verbose_name='Text color (hover)'),
        ),
    ]
