# Generated by Django 3.0.10 on 2020-09-20 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0006_formsection_form_submit_button_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formsection',
            name='search_image',
        ),
    ]
