# Generated by Django 3.0.10 on 2020-09-20 20:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0022_uploadedimage'),
        ('components', '0007_remove_formsection_search_image'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='formsection',
            name='intro',
        ),
        migrations.AddField(
            model_name='featuresection',
            name='section_padding_basic',
            field=models.CharField(choices=[('py-0', 'None'), ('py-2', 'Small'), ('py-4', 'Medium'), ('py-6', 'Large'), ('py-8', 'X-Large')], default='py-4', max_length=50, null=True, verbose_name='Padding top'),
        ),
        migrations.AddField(
            model_name='formsection',
            name='section_padding_basic',
            field=models.CharField(choices=[('py-0', 'None'), ('py-2', 'Small'), ('py-4', 'Medium'), ('py-6', 'Large'), ('py-8', 'X-Large')], default='py-4', max_length=50, null=True, verbose_name='Padding top'),
        ),
        migrations.AddField(
            model_name='herosection',
            name='section_padding_basic',
            field=models.CharField(choices=[('py-0', 'None'), ('py-2', 'Small'), ('py-4', 'Medium'), ('py-6', 'Large'), ('py-8', 'X-Large')], default='py-4', max_length=50, null=True, verbose_name='Padding top'),
        ),
        migrations.AlterField(
            model_name='featuresection',
            name='section_background_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtailimages.Image', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='featuresection',
            name='section_background_type',
            field=models.CharField(blank=True, choices=[('transparent', 'Transparent'), ('solid', 'Solid Color'), ('gradient', 'Gradient Color'), ('image', 'Background Image')], default='trasparent', help_text='Transparent background will use the background-color "page settings".', max_length=100, null=True, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='formsection',
            name='section_background_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtailimages.Image', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='formsection',
            name='section_background_type',
            field=models.CharField(blank=True, choices=[('transparent', 'Transparent'), ('solid', 'Solid Color'), ('gradient', 'Gradient Color'), ('image', 'Background Image')], default='trasparent', help_text='Transparent background will use the background-color "page settings".', max_length=100, null=True, verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='herosection',
            name='section_background_image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='wagtailimages.Image', verbose_name='Image'),
        ),
        migrations.AlterField(
            model_name='herosection',
            name='section_background_type',
            field=models.CharField(blank=True, choices=[('transparent', 'Transparent'), ('solid', 'Solid Color'), ('gradient', 'Gradient Color'), ('image', 'Background Image')], default='trasparent', help_text='Transparent background will use the background-color "page settings".', max_length=100, null=True, verbose_name='Type'),
        ),
    ]
