# Generated by Django 3.0.10 on 2020-09-20 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0008_auto_20200920_2028'),
    ]

    operations = [
        migrations.AddField(
            model_name='featuresection',
            name='section_container_basic',
            field=models.CharField(choices=[('container max-w-2xl', 'Small'), ('container max-w-4xl', 'Medium'), ('container', 'Large'), ('container max-w-full', 'Full')], default='container', max_length=50, null=True, verbose_name='Size'),
        ),
        migrations.AddField(
            model_name='formsection',
            name='section_container_basic',
            field=models.CharField(choices=[('container max-w-2xl', 'Small'), ('container max-w-4xl', 'Medium'), ('container', 'Large'), ('container max-w-full', 'Full')], default='container', max_length=50, null=True, verbose_name='Size'),
        ),
        migrations.AddField(
            model_name='herosection',
            name='section_container_basic',
            field=models.CharField(choices=[('container max-w-2xl', 'Small'), ('container max-w-4xl', 'Medium'), ('container', 'Large'), ('container max-w-full', 'Full')], default='container', max_length=50, null=True, verbose_name='Size'),
        ),
        migrations.AlterField(
            model_name='featuresection',
            name='section_padding_basic',
            field=models.CharField(choices=[('py-0', 'None'), ('py-24', 'Small'), ('py-40', 'Medium'), ('py-56', 'Large'), ('py-64', 'X-Large')], default='py-40', max_length=50, null=True, verbose_name='Size'),
        ),
        migrations.AlterField(
            model_name='formsection',
            name='section_padding_basic',
            field=models.CharField(choices=[('py-0', 'None'), ('py-24', 'Small'), ('py-40', 'Medium'), ('py-56', 'Large'), ('py-64', 'X-Large')], default='py-40', max_length=50, null=True, verbose_name='Size'),
        ),
        migrations.AlterField(
            model_name='herosection',
            name='section_padding_basic',
            field=models.CharField(choices=[('py-0', 'None'), ('py-24', 'Small'), ('py-40', 'Medium'), ('py-56', 'Large'), ('py-64', 'X-Large')], default='py-40', max_length=50, null=True, verbose_name='Size'),
        ),
    ]
