# Generated by Django 3.0.10 on 2020-09-20 21:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0010_auto_20200920_2111'),
    ]

    operations = [
        migrations.AddField(
            model_name='featuresection',
            name='section_color_theme',
            field=models.CharField(blank=True, choices=[('light', 'Light'), ('dark', 'Dark')], max_length=50, null=True, verbose_name='Theme'),
        ),
        migrations.AddField(
            model_name='formsection',
            name='section_color_theme',
            field=models.CharField(blank=True, choices=[('light', 'Light'), ('dark', 'Dark')], max_length=50, null=True, verbose_name='Theme'),
        ),
        migrations.AddField(
            model_name='herosection',
            name='section_color_theme',
            field=models.CharField(blank=True, choices=[('light', 'Light'), ('dark', 'Dark')], max_length=50, null=True, verbose_name='Theme'),
        ),
    ]
