# Generated by Django 3.0.10 on 2020-09-20 22:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0011_auto_20200920_2122'),
    ]

    operations = [
        migrations.AddField(
            model_name='formsection',
            name='title_font_size',
            field=models.CharField(blank=True, choices=[('text-2xl', 'X-Small'), ('text-3xl', 'Small'), ('text-4xl', 'Medium'), ('text-5xl', 'Large'), ('text-6xl', 'X-Large')], max_length=50, null=True, verbose_name='Font Size'),
        ),
        migrations.AddField(
            model_name='formsection',
            name='title_font_weight',
            field=models.CharField(blank=True, choices=[('font-hairline', 'Hairline'), ('font-thin', 'Thin'), ('font-light', 'Light'), ('font-normal', 'Normal'), ('font-medium', 'Medium'), ('font-bold', 'Bold')], max_length=50, null=True, verbose_name='Font Weight'),
        ),
    ]
