# Generated by Django 3.0.10 on 2020-09-21 20:32

from django.db import migrations, models
import wagtail_color_panel.fields


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0013_auto_20200921_2001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formsection',
            name='button_action_bg_color',
            field=wagtail_color_panel.fields.ColorField(blank=True, help_text="Disable 'Color Type' to activate this field.", max_length=7, null=True, verbose_name='Color'),
        ),
        migrations.AlterField(
            model_name='formsection',
            name='button_action_bg_color_hover',
            field=wagtail_color_panel.fields.ColorField(blank=True, max_length=7, null=True, verbose_name='Color (hover)'),
        ),
        migrations.AlterField(
            model_name='formsection',
            name='button_action_bg_color_type',
            field=models.CharField(blank=True, choices=[('primary', 'Primary Color'), ('secondary', 'Secondary Color')], default='primary', help_text='Define primary and secondarz color in tab <a href="./#tab-branding">here</a>.', max_length=50, null=True, verbose_name='Color Type'),
        ),
        migrations.AlterField(
            model_name='formsection',
            name='button_action_border_radius',
            field=models.CharField(blank=True, choices=[('rounded-none', 'None'), ('rounded-sm', 'Small'), ('rounded-md', 'Medium'), ('rounded-lg', 'Large'), ('rounded-full', 'Full')], max_length=50, null=True, verbose_name='Edges'),
        ),
        migrations.AlterField(
            model_name='formsection',
            name='button_action_font_weight',
            field=models.CharField(blank=True, choices=[('font-hairline', 'Hairline'), ('font-thin', 'Thin'), ('font-light', 'Light'), ('font-normal', 'Default'), ('font-hairline', 'Hailine'), ('font-medium', 'Medium'), ('font-semibold', 'Semibold'), ('font-bold', 'Bold'), ('font-extrabold', 'Extrabold'), ('font-black', 'Black')], default='font-normal', max_length=50, null=True, verbose_name='Font weight'),
        ),
        migrations.AlterField(
            model_name='formsection',
            name='button_action_padding',
            field=models.CharField(blank=True, choices=[('px-1 py-1', 'Small'), ('px-4 py-4', 'Medium'), ('px-8 py-8', 'Large'), ('px-12 py-12', 'X-Large')], max_length=50, null=True, verbose_name='Size'),
        ),
        migrations.AlterField(
            model_name='formsection',
            name='button_action_text_color',
            field=wagtail_color_panel.fields.ColorField(blank=True, max_length=7, null=True, verbose_name='Text color'),
        ),
        migrations.AlterField(
            model_name='formsection',
            name='button_action_text_color_hover',
            field=wagtail_color_panel.fields.ColorField(blank=True, max_length=7, null=True, verbose_name='Text color (hover)'),
        ),
        migrations.AlterField(
            model_name='herosection',
            name='button_action_bg_color',
            field=wagtail_color_panel.fields.ColorField(blank=True, help_text="Disable 'Color Type' to activate this field.", max_length=7, null=True, verbose_name='Color'),
        ),
        migrations.AlterField(
            model_name='herosection',
            name='button_action_bg_color_hover',
            field=wagtail_color_panel.fields.ColorField(blank=True, max_length=7, null=True, verbose_name='Color (hover)'),
        ),
        migrations.AlterField(
            model_name='herosection',
            name='button_action_bg_color_type',
            field=models.CharField(blank=True, choices=[('primary', 'Primary Color'), ('secondary', 'Secondary Color')], default='primary', help_text='Define primary and secondarz color in tab <a href="./#tab-branding">here</a>.', max_length=50, null=True, verbose_name='Color Type'),
        ),
        migrations.AlterField(
            model_name='herosection',
            name='button_action_border_radius',
            field=models.CharField(blank=True, choices=[('rounded-none', 'None'), ('rounded-sm', 'Small'), ('rounded-md', 'Medium'), ('rounded-lg', 'Large'), ('rounded-full', 'Full')], max_length=50, null=True, verbose_name='Edges'),
        ),
        migrations.AlterField(
            model_name='herosection',
            name='button_action_font_weight',
            field=models.CharField(blank=True, choices=[('font-hairline', 'Hairline'), ('font-thin', 'Thin'), ('font-light', 'Light'), ('font-normal', 'Default'), ('font-hairline', 'Hailine'), ('font-medium', 'Medium'), ('font-semibold', 'Semibold'), ('font-bold', 'Bold'), ('font-extrabold', 'Extrabold'), ('font-black', 'Black')], default='font-normal', max_length=50, null=True, verbose_name='Font weight'),
        ),
        migrations.AlterField(
            model_name='herosection',
            name='button_action_padding',
            field=models.CharField(blank=True, choices=[('px-1 py-1', 'Small'), ('px-4 py-4', 'Medium'), ('px-8 py-8', 'Large'), ('px-12 py-12', 'X-Large')], max_length=50, null=True, verbose_name='Size'),
        ),
        migrations.AlterField(
            model_name='herosection',
            name='button_action_text_color',
            field=wagtail_color_panel.fields.ColorField(blank=True, max_length=7, null=True, verbose_name='Text color'),
        ),
        migrations.AlterField(
            model_name='herosection',
            name='button_action_text_color_hover',
            field=wagtail_color_panel.fields.ColorField(blank=True, max_length=7, null=True, verbose_name='Text color (hover)'),
        ),
    ]
