# Generated by Django 3.0.10 on 2020-09-21 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0014_auto_20200921_2032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='featuresection',
            name='section_container_width',
            field=models.CharField(blank=True, choices=[('container max-w-2xl', 'Small'), ('container max-w-4xl', 'Medium'), ('container', 'Large'), ('container max-w-full', 'Full')], default='container', max_length=50, null=True, verbose_name='Width'),
        ),
        migrations.AlterField(
            model_name='featuresection',
            name='section_description',
            field=models.TextField(blank=True, default='The thing we do is better than any other similar thing and this hero panel will convince you of that, just by having a glorious background image.', help_text='Leave field empty to hide.', max_length=400, null=True, verbose_name='Hero description'),
        ),
        migrations.AlterField(
            model_name='featuresection',
            name='section_subheading',
            field=models.CharField(blank=True, default='What business are you?', help_text="Leave field empty to hide. <a href='/contract.pdf'>contract</a>.", max_length=100, null=True, verbose_name='Hero subtitle'),
        ),
        migrations.AlterField(
            model_name='featuresection',
            name='section_top_bottom_padding',
            field=models.CharField(blank=True, choices=[('py-0', 'None'), ('py-24', 'Small'), ('py-40', 'Medium'), ('py-56', 'Large'), ('py-64', 'X-Large')], default='py-40', max_length=50, null=True, verbose_name='Height'),
        ),
        migrations.AlterField(
            model_name='formsection',
            name='button_action_bg_color_type',
            field=models.CharField(blank=True, choices=[('primary', 'Primary Color'), ('secondary', 'Secondary Color'), ('custom', 'Custom Color')], default='primary', help_text='Define primary and secondarz color in tab <a href="./#tab-branding">here</a>.', max_length=50, null=True, verbose_name='Color type'),
        ),
        migrations.AlterField(
            model_name='formsection',
            name='section_container_width',
            field=models.CharField(blank=True, choices=[('container max-w-2xl', 'Small'), ('container max-w-4xl', 'Medium'), ('container', 'Large'), ('container max-w-full', 'Full')], default='container', max_length=50, null=True, verbose_name='Width'),
        ),
        migrations.AlterField(
            model_name='formsection',
            name='section_description',
            field=models.TextField(blank=True, default='The thing we do is better than any other similar thing and this hero panel will convince you of that, just by having a glorious background image.', help_text='Leave field empty to hide.', max_length=400, null=True, verbose_name='Hero description'),
        ),
        migrations.AlterField(
            model_name='formsection',
            name='section_subheading',
            field=models.CharField(blank=True, default='What business are you?', help_text="Leave field empty to hide. <a href='/contract.pdf'>contract</a>.", max_length=100, null=True, verbose_name='Hero subtitle'),
        ),
        migrations.AlterField(
            model_name='formsection',
            name='section_top_bottom_padding',
            field=models.CharField(blank=True, choices=[('py-0', 'None'), ('py-24', 'Small'), ('py-40', 'Medium'), ('py-56', 'Large'), ('py-64', 'X-Large')], default='py-40', max_length=50, null=True, verbose_name='Height'),
        ),
        migrations.AlterField(
            model_name='herosection',
            name='button_action_bg_color_type',
            field=models.CharField(blank=True, choices=[('primary', 'Primary Color'), ('secondary', 'Secondary Color'), ('custom', 'Custom Color')], default='primary', help_text='Define primary and secondarz color in tab <a href="./#tab-branding">here</a>.', max_length=50, null=True, verbose_name='Color type'),
        ),
        migrations.AlterField(
            model_name='herosection',
            name='section_container_width',
            field=models.CharField(blank=True, choices=[('container max-w-2xl', 'Small'), ('container max-w-4xl', 'Medium'), ('container', 'Large'), ('container max-w-full', 'Full')], default='container', max_length=50, null=True, verbose_name='Width'),
        ),
        migrations.AlterField(
            model_name='herosection',
            name='section_description',
            field=models.TextField(blank=True, default='The thing we do is better than any other similar thing and this hero panel will convince you of that, just by having a glorious background image.', help_text='Leave field empty to hide.', max_length=400, null=True, verbose_name='Hero description'),
        ),
        migrations.AlterField(
            model_name='herosection',
            name='section_subheading',
            field=models.CharField(blank=True, default='What business are you?', help_text="Leave field empty to hide. <a href='/contract.pdf'>contract</a>.", max_length=100, null=True, verbose_name='Hero subtitle'),
        ),
        migrations.AlterField(
            model_name='herosection',
            name='section_top_bottom_padding',
            field=models.CharField(blank=True, choices=[('py-0', 'None'), ('py-24', 'Small'), ('py-40', 'Medium'), ('py-56', 'Large'), ('py-64', 'X-Large')], default='py-40', max_length=50, null=True, verbose_name='Height'),
        ),
    ]
