# Generated by Django 3.0.10 on 2020-09-22 05:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0016_auto_20200922_0506'),
    ]

    operations = [
        migrations.AddField(
            model_name='formfield',
            name='field_layout',
            field=models.CharField(blank=True, choices=[('py-0', 'None'), ('py-24', 'Small'), ('py-40', 'Medium'), ('py-56', 'Large'), ('py-64', 'X-Large')], default='py-40', max_length=50, null=True, verbose_name='Height'),
        ),
    ]
