# Generated by Django 3.0.10 on 2020-09-22 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0017_formfield_field_layout'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formfield',
            name='field_layout',
            field=models.CharField(choices=[('full', 'Full width'), ('half', 'Half width'), ('third', 'Third width'), ('quarter', 'Quarter width')], default='full', max_length=50, null=True, verbose_name='Field width'),
        ),
    ]
