# Generated by Django 3.0.10 on 2020-09-23 20:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('components', '0018_auto_20200922_0545'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='formsection',
            options={'verbose_name': 'Form Section', 'verbose_name_plural': 'Form Sections'},
        ),
    ]
