# Generated by Django 3.0.10 on 2020-09-23 20:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailcore', '0052_pagelogentry'),
        ('components', '0019_auto_20200923_2012'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='herosection',
            name='id',
        ),
        migrations.AddField(
            model_name='herosection',
            name='page_ptr',
            field=models.OneToOneField(auto_created=True, default=1, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page'),
            preserve_default=False,
        ),
    ]
