# Generated by Django 3.0.10 on 2020-09-26 15:14

from django.db import migrations, models
import django.db.models.deletion
import wagtail_color_panel.fields


class Migration(migrations.Migration):

    dependencies = [
        ('wagtailimages', '0022_uploadedimage'),
        ('wagtailcore', '0052_pagelogentry'),
        ('components', '0021_auto_20200923_2110'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubscriptionSection',
            fields=[
                ('page_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='wagtailcore.Page')),
                ('section_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Title')),
                ('section_heading', models.CharField(blank=True, default='We are heroes', max_length=100, null=True, verbose_name='Hero title')),
                ('section_subheading', models.CharField(blank=True, default='What business are you?', help_text="Leave field empty to hide. <a href='/contract.pdf'>contract</a>.", max_length=100, null=True, verbose_name='Hero subtitle')),
                ('section_description', models.TextField(blank=True, default='The thing we do is better than any other similar thing and this hero panel will convince you of that, just by having a glorious background image.', help_text='Leave field empty to hide.', max_length=400, null=True, verbose_name='Hero description')),
                ('section_background_type', models.CharField(blank=True, choices=[('transparent', 'Transparent'), ('solid', 'Solid Color'), ('gradient', 'Gradient Color'), ('image', 'Background Image')], default='trasparent', help_text='Transparent background will use the background-color "page settings".', max_length=100, null=True, verbose_name='Type')),
                ('section_background_color', wagtail_color_panel.fields.ColorField(blank=True, help_text='Choose background color', max_length=7, null=True, verbose_name='Color 1')),
                ('section_background_color_2', wagtail_color_panel.fields.ColorField(blank=True, help_text='Choose background color', max_length=7, null=True, verbose_name='Color 2')),
                ('section_color_theme', models.CharField(blank=True, choices=[('light', 'Light'), ('dark', 'Dark')], max_length=50, null=True, verbose_name='Theme')),
                ('section_top_bottom_padding', models.CharField(blank=True, choices=[('py-0', 'None'), ('py-24', 'Small'), ('py-40', 'Medium'), ('py-56', 'Large'), ('py-64', 'X-Large')], default='py-40', max_length=50, null=True, verbose_name='Height')),
                ('section_container_width', models.CharField(blank=True, choices=[('container max-w-2xl', 'Small'), ('container max-w-4xl', 'Medium'), ('container', 'Large'), ('container max-w-full', 'Full')], default='container', max_length=50, null=True, verbose_name='Width')),
                ('button_action_bg_color_type', models.CharField(blank=True, choices=[('primary', 'Primary Color'), ('secondary', 'Secondary Color'), ('custom', 'Custom Color')], default='primary', help_text='Define primary and secondarz color in tab <a href="./#tab-branding">here</a>.', max_length=50, null=True, verbose_name='Color type')),
                ('button_action_bg_color', wagtail_color_panel.fields.ColorField(blank=True, help_text="Disable 'Color Type' to activate this field.", max_length=7, null=True, verbose_name='Color')),
                ('button_action_bg_color_hover', wagtail_color_panel.fields.ColorField(blank=True, max_length=7, null=True, verbose_name='Color (hover)')),
                ('button_action_text_color', wagtail_color_panel.fields.ColorField(blank=True, max_length=7, null=True, verbose_name='Text color')),
                ('button_action_text_color_hover', wagtail_color_panel.fields.ColorField(blank=True, max_length=7, null=True, verbose_name='Text color (hover)')),
                ('button_action_font_weight', models.CharField(blank=True, choices=[('font-hairline', 'Hairline'), ('font-thin', 'Thin'), ('font-light', 'Light'), ('font-normal', 'Default'), ('font-hairline', 'Hailine'), ('font-medium', 'Medium'), ('font-semibold', 'Semibold'), ('font-bold', 'Bold'), ('font-extrabold', 'Extrabold'), ('font-black', 'Black')], default='font-normal', max_length=50, null=True, verbose_name='Font weight')),
                ('button_action_padding', models.CharField(blank=True, choices=[('px-1 py-1', 'Small'), ('px-4 py-4', 'Medium'), ('px-8 py-8', 'Large'), ('px-12 py-12', 'X-Large')], max_length=50, null=True, verbose_name='Size')),
                ('button_action_border_radius', models.CharField(blank=True, choices=[('rounded-none', 'None'), ('rounded-sm', 'Small'), ('rounded-md', 'Medium'), ('rounded-lg', 'Large'), ('rounded-full', 'Full')], max_length=50, null=True, verbose_name='Edges')),
                ('title_font_size', models.CharField(blank=True, choices=[('text-2xl', 'X-Small'), ('text-3xl', 'Small'), ('text-4xl', 'Medium'), ('text-5xl', 'Large'), ('text-6xl', 'X-Large')], max_length=50, null=True, verbose_name='Font Size')),
                ('title_font_weight', models.CharField(blank=True, choices=[('font-thin', 'Thin'), ('font-light', 'Light'), ('font-normal', 'Normal'), ('font-medium', 'Medium'), ('font-bold', 'Bold')], max_length=50, null=True, verbose_name='Font Weight')),
                ('subscription_layout', models.CharField(blank=True, choices=[('simple_centered', 'Simple centered'), ('image_right', 'Image on right')], default='simple_centered', max_length=100, verbose_name='Layout')),
                ('section_background_image', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='wagtailimages.Image', verbose_name='Image')),
            ],
            options={
                'abstract': False,
            },
            bases=('wagtailcore.page', models.Model),
        ),
    ]
