# Generated by Django 3.0.9 on 2020-08-26 09:12

from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_store_related_products'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='store',
            managers=[
                ('products', django.db.models.manager.Manager()),
            ],
        ),
    ]
