# Generated by Django 3.0.9 on 2020-08-26 09:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_auto_20200826_0912'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='store',
            name='related_products',
        ),
    ]
