# Generated by Django 3.0.9 on 2020-08-26 09:46

from django.db import migrations
import django.db.models.deletion
import modelcluster.fields


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_remove_store_related_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='related_store',
            field=modelcluster.fields.ParentalKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='related_products', to='shop.Store'),
        ),
    ]
